<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c) 2012 NVIDIA Corporation.  All Rights Reserved.

     NVIDIA Corporation and its licensors retain all intellectual property and
     proprietary rights in and to this software and related documentation.  Any
     use, reproduction, disclosure or distribution of this software and related
     documentation without an express license agreement from NVIDIA Corporation
     is strictly prohibited.
 */
-->
<!DOCTYPE AudioConfigs [
  <!ELEMENT AudioConfigs (alsa_device)>
  <!ELEMENT alsa_device (pcm_config, playback, capture, call)>
  <!ELEMENT playback (pcm_config, device, path)>
  <!ELEMENT capture (pcm_config, device, path)>
  <!ELEMENT voice-call (pcm_config, device, path)>
  <!ELEMENT device (path)>
  <!ELEMENT path (ctl, at)>
  <!ELEMENT alsa_device EMPTY>
  <!ATTLIST alsa_device name (music|voice|aux|voice-call|bt-voice-call) #REQUIRED>
  <!ATTLIST alsa_device card_id CDATA #REQUIRED>
  <!ATTLIST alsa_device card_name CDATA #REQUIRED>
  <!ATTLIST alsa_device device_id CDATA #REQUIRED>
  <!ELEMENT alsa_device EMPTY>
  <!ELEMENT pcm_config EMPTY>
  <!ATTLIST pcm_config rate (8000|11025|16000|22050|32000|44100|48000|64000|88200|96000|176400|192000) #IMPLIED>
  <!ATTLIST pcm_config channels (1|2|3|4|5|6|7|8) #IMPLIED>
  <!ATTLIST pcm_config bps (16|32) #IMPLIED>
  <!ATTLIST pcm_config period_size CDATA #IMPLIED>
  <!ATTLIST pcm_config period_count CDATA #IMPLIED>
  <!ATTLIST pcm_config start_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config stop_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config silence_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config avail_min CDATA #IMPLIED>
  <!ELEMENT pcm_config EMPTY>
  <!ELEMENT device EMPTY>
  <!ATTLIST device name (speaker|headphone|earpiece|bt-sco|aux|builtin-mic|headset-mic|bt-sco-mic|voice-call|bt-voice-call) #REQUIRED>
  <!ELEMENT device EMPTY>
  <!ELEMENT path EMPTY>
  <!ATTLIST path name CDATA #IMPLIED>
  <!ELEMENT path EMPTY>
  <!ELEMENT param EMPTY>
  <!ATTLIST param name CDATA #REQUIRED>
  <!ATTLIST param val CDATA #REQUIRED>
  <!ELEMENT param EMPTY>
  <!ELEMENT ctl EMPTY>
  <!ATTLIST ctl name CDATA #REQUIRED>
  <!ATTLIST ctl val CDATA #REQUIRED>
  <!ELEMENT ctl EMPTY>
  <!ELEMENT at EMPTY>
  <!ATTLIST at node CDATA #REQUIRED>
  <!ATTLIST at cmd CDATA #REQUIRED>
  <!ELEMENT at EMPTY>
]>
<!--
     This file is used to declare various board specific audio configs
-->

<AudioConfigs>

  <alsa_device name ="aux"
             card_id="0"
             card_name="Tegra"
             device_id="3">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <param name="HW Rates" val="48000 44100"/>
    <playback>
      <device name="aux"/>
    </playback>
  </alsa_device>

  <alsa_device name="wfd">
    <pcm_config rate="48000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"/>
    <playback>
      <device name="wfd"/>
    </playback>
  </alsa_device>
  
  <alsa_device name="music"
             card_id="1"
             card_name="tegraaic325x"
             device_id="0">
    <pcm_config rate="44100"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>

    <param name="ulp" val="1"/>
    <param name="I2S Master" val="1"/>

    <path>
      <!--ASI to MiniDsp connections (TODO: Change later when call moves to voice port)-->
      <!--playback paths-->
      <!--ctl name="PCM Playback Volume" val="135"/-->
      <ctl name="HP Driver Gain" val="8"/>
      <!--ctl name="Speaker Amplifier Volume" val="1"/-->
      <!--ctl name="Receiver Amplifier Volume" val="10"/-->
      <ctl name="Line Driver Gain" val="10"/>
      <ctl name="DAC Digital Volume Control" val="115"/>
      <ctl name="DAC PRB Selection(1 to 25)" val="24"/>
      <ctl name="ADC PRB Selection(1 to 18)" val="2"/>
      <ctl name="HP_gnd_centred_mode_ctrl" val="1"/>
      <!--capture paths-->
      <!--ctl name="MicPGA Volume Control" val="50"/ -->
      <!--ctl name="PCM Capture Volume" val="24"/ -->
      <ctl name="Mic_Bias_Power_ctrl" val="1"/>
      <ctl name="Beep Length MID" val="1"/>
      <ctl name="Right ADC Route" val="Analog"/>
      <ctl name="Left ADC Route" val="Analog"/>
      <ctl name="ADC Digital Volume Control" val="29"/>
    </path>

    <playback>
      <device name="headphone">
        <path name="on">
          <ctl name="Codec Firmware Setmode" val="Music Playback Headphones"/>
	  <ctl name="Eq Ctrl Switch" val="0"/>
          <ctl name="HPR Output Mixer R_DAC switch" val="1"/>
          <ctl name="HPL Output Mixer L_DAC switch" val="1"/>
          <ctl name="Headphone jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headphone jack Switch" val="0"/>
	  <ctl name="HPR Output Mixer R_DAC switch" val="0"/>
          <ctl name="HPL Output Mixer L_DAC switch" val="0"/>
          <ctl name="Eq Ctrl Switch" val="1"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
	  <ctl name="Codec Firmware Setmode" val="Music Playback Speaker"/>
	  <ctl name="Eq Ctrl Switch" val="1"/>
          <ctl name="LOL Output Mixer L_DAC switch" val="1"/>
       	  <ctl name="LOR Output Mixer R_DAC switch" val="1"/>	  
        </path>
        <path name="off">
          <ctl name="Spk Ctrl Switch" val="0" />
          <ctl name="LOL Output Mixer L_DAC switch" val="0"/>
      	  <ctl name="LOR Output Mixer R_DAC switch" val="0"/>
	  <ctl name="Eq Ctrl Switch" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
        </path>
        <path name="off">
        </path>
      </device>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>

      <device name="builtin-mic">
        <path name="on">
          <ctl name="Codec Firmware Setmode" val="Voice Record On Board Mic"/>
          <ctl name="L_R_MICPGA_Vol_Ctrl" val="58"/>
          <ctl name="Int Mic Switch" val="1"/>
          <ctl name="Left Input Mixer IN2_L switch" val="1" />
          <ctl name="Left Input Mixer IN2_R switch" val="1"/>
   	  <ctl name="ADC Eq Ctrl Switch" val="0"/>
        </path>
        <path name="off">
          <ctl name="Left Input Mixer IN2_L switch" val="0" />
          <ctl name="Left Input Mixer IN2_R switch" val="0"/>
          <ctl name="Int Mic Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
	  <ctl name="Codec Firmware Setmode" val="Voice Record Headset Mic"/>
	      <ctl name="L_R_MICPGA_Vol_Ctrl" val="64"/>
          <ctl name="Mic Jack Switch" val="1"/>
          <ctl name="Right Input Mixer IN1_R switch" val="1"/>
          <ctl name="Right Input Mixer CM1R switch" val="1"/>
   	  <ctl name="ADC Eq Ctrl Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Right Input Mixer IN1_R switch" val="0"/>
          <ctl name="Right Input Mixer CM1R switch" val="0"/>
          <ctl name="Mic Jack Switch" val="0"/>
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name="voice"
               card_id="-1"
               card_name="tegraaic325x"
               device_id="2">
    <pcm_config rate="8000"
                channels="1"
                bps="16"
                period_size="256"
                period_count="4"
                start_threshold="1023"
                stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>
    <playback>
      <device name="bt-sco"/>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="bt-sco-mic"/>
    </capture>
  </alsa_device>
</AudioConfigs>
